# Generated by Django 6.0.6 on 2026-06-25 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='fecha_nacimiento',
        ),
    ]
